# Generated by Django 4.0.1 on 2022-02-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date',
            new_name='date_create',
        ),
        migrations.AddField(
            model_name='todo',
            name='date_complete',
            field=models.DateTimeField(null=True),
        ),
    ]
