# Generated by Django 4.0.1 on 2022-02-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_date_todo_date_create_todo_date_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
